[project]
name = "{{ cookiecutter.hyphenated }}"
version = "0.1.0"
description = "{{ cookiecutter.description or "" }}"
readme = "README.md"
authors = [{name = "{{ cookiecutter.author_name }}"}]
requires-python = ">=3.13"
dependencies = [
    "django>=5.2",
    "psycopg2-binary>=2.9.10",
]
